"""Per-state unclaimed-property filing reference.

Auto-generated from research (50 states + DC). Used by the unsupported-state
handoff UI to deep-link members to their state's official portal with steps.
Regenerate via scripts/gen helper if portals change.
Generated: 2026-06-03
"""

STATES: dict[str, dict] = {'AK': {'agency': 'Alaska Department of Revenue, Treasury Division, Unclaimed Property Program',
        'free_note': 'There is no charge to search or file a claim with the Alaska Treasury '
                     'Division.',
        'name': 'Alaska',
        'portal_url': 'https://unclaimedproperty.alaska.gov/',
        'processing_time': '30-90 days',
        'steps': ['Go to the portal and search by your name or business name',
                  'Browse the returned matches and select the properties that belong to you',
                  'Start the claim and verify the listed property details',
                  'Fill in the online claimant information form',
                  'Attach proof of identity and proof of address (and ownership documents if '
                  'requested)',
                  'Submit electronically and save your confirmation/claim number']},
 'AL': {'agency': 'Office of the Alabama State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming is completely free directly through the Alabama State '
                     'Treasurer.',
        'name': 'Alabama',
        'portal_url': 'https://alabama.findyourunclaimedproperty.com/',
        'processing_time': '60-90 days',
        'steps': ['Open the search portal and enter your first and last name (add city to narrow '
                  'results)',
                  'Review the list of matching properties and select any that appear to be yours',
                  'Click to start a claim and confirm the properties you want to claim',
                  'Complete the online claimant form with your address, SSN, and contact details',
                  'Upload required ID and proof-of-address documents, or print and mail the claim '
                  'form if requested',
                  'Submit and note your claim ID to track status']},
 'AR': {'agency': 'Arkansas Auditor of State, Unclaimed Property Division (Great Arkansas Treasure '
                  'Hunt)',
        'free_note': 'Claiming property directly through the Arkansas Auditor of State is always '
                     'free.',
        'name': 'Arkansas',
        'portal_url': 'https://arkansas.findyourunclaimedproperty.com/',
        'processing_time': '60-90 days',
        'steps': ['Enter your name in the search box on the portal',
                  'Review matches and check the boxes for properties you believe are yours',
                  'Click to file a claim and confirm the selected properties',
                  'Complete the claimant form with your contact and identifying information',
                  'Upload or mail the required identification and proof-of-address documents',
                  'Submit the claim and keep the claim ID to follow up']},
 'AZ': {'agency': 'Arizona Department of Revenue, Unclaimed Property Unit',
        'free_note': 'Arizona never charges owners to search for or claim their property.',
        'name': 'Arizona',
        'portal_url': 'https://azunclaimed.gov/',
        'processing_time': '60-90 days',
        'steps': ['Search the database by entering your name (and optionally city)',
                  'Select any matching property records that appear to be yours',
                  'Add them to a claim and begin the online claim process',
                  'Enter your claimant details and relationship to the property',
                  'Upload a government-issued ID and proof of your current/past address',
                  'Submit the claim and record the claim ID for status checks']},
 'CA': {'agency': "California State Controller's Office",
        'free_note': 'It is free to search and claim directly with the California State '
                     "Controller's Office.",
        'name': 'California',
        'portal_url': 'https://claimit.ca.gov/',
        'processing_time': '30-180 days',
        'steps': ['Open claimit.ca.gov and search by your name or business name',
                  'Review the list of properties and select those that match you',
                  'Start a claim and confirm the property details',
                  'Enter your claimant information and answer ownership questions',
                  'Upload the required identity and address documents (some claims are '
                  'auto-approved without documents)',
                  'Submit and use your claim ID to check status online']},
 'CO': {'agency': 'Colorado Department of the Treasury (Great Colorado Payback)',
        'free_note': 'The Great Colorado Payback returns property for free; no fee to search or '
                     'claim.',
        'name': 'Colorado',
        'portal_url': 'https://unclaimedproperty.colorado.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the portal using your name (and city if needed)',
                  'Select any matching properties from the results',
                  'Begin the claim and verify the property details',
                  'Fill out the online claimant information form',
                  'Upload proof of identity and proof of address as instructed',
                  'Submit the claim and note the claim ID for tracking']},
 'CT': {'agency': 'Office of the Connecticut State Treasurer (CT Big List)',
        'free_note': 'Searching and claiming directly with the Connecticut Treasurer is free.',
        'name': 'Connecticut',
        'portal_url': 'https://ctbiglist.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search CT Big List by entering your name',
                  'Review the matching records and select your properties',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant form with your details',
                  'Upload or mail the requested identity and address documentation',
                  'Submit and retain your claim confirmation number']},
 'DC': {'agency': 'District of Columbia Office of the Chief Financial Officer, Unclaimed Property '
                  'Unit',
        'free_note': 'The District does not charge a fee to search for or claim property.',
        'name': 'District of Columbia',
        'portal_url': 'https://unclaimedproperty.dc.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the DC portal by entering your name or business name',
                  'Select any matching properties that belong to you',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and note your claim ID for status checks']},
 'DE': {'agency': 'Delaware Office of Unclaimed Property (Department of Finance)',
        'free_note': 'Delaware does not charge owners to find or claim their property.',
        'name': 'Delaware',
        'portal_url': 'https://unclaimedproperty.delaware.gov/',
        'processing_time': '30-90 days',
        'steps': ['Enter your name in the portal search field',
                  'Review the returned matches and select your properties',
                  'Start the claim and confirm the property details',
                  'Complete the claimant information form online',
                  'Upload the required ID and proof-of-address documents',
                  'Submit the claim and save the claim ID to monitor status']},
 'FL': {'agency': 'Florida Department of Financial Services, Division of Unclaimed Property',
        'free_note': 'Florida returns unclaimed property for free; no fee to search or file '
                     'directly.',
        'name': 'Florida',
        'portal_url': 'https://www.fltreasurehunt.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search FloridaTreasureHunt by your name or business name',
                  'Select the properties that appear to belong to you',
                  'Click to begin a claim and confirm the property details',
                  'Complete the online claimant form with your information',
                  'Upload proof of identity and proof of address (and ownership documents if '
                  'requested)',
                  'Submit electronically and note your claim number for tracking']},
 'GA': {'agency': 'Georgia Department of Revenue, Unclaimed Property Program',
        'free_note': 'It is always free to search and claim through the Georgia Department of '
                     'Revenue.',
        'name': 'Georgia',
        'portal_url': 'https://gaclaims.unclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the portal by entering your name',
                  'Review matches and select the properties you want to claim',
                  'Start the claim and confirm the selected properties',
                  'Fill in the online claimant information form',
                  'Upload required identification and proof-of-address documents',
                  'Submit the claim and record the claim ID for status checks']},
 'HI': {'agency': 'Hawaii Department of Budget and Finance, Unclaimed Property Program',
        'free_note': 'Hawaii returns property to owners at no charge.',
        'name': 'Hawaii',
        'portal_url': 'https://unclaimedproperty.ehawaii.gov/',
        'processing_time': '60-120 days',
        'steps': ['Search the eHawaii portal by your name or business name',
                  'Review the matching records and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the claimant form with your contact and ID information',
                  'Print, sign, and mail the claim form with required documents if instructed',
                  'Submit and keep the claim reference to follow up']},
 'IA': {'agency': 'Iowa State Treasurer (Great Iowa Treasure Hunt)',
        'free_note': 'The Great Iowa Treasure Hunt is free; the state never charges to return '
                     'property.',
        'name': 'Iowa',
        'portal_url': 'https://www.greatiowatreasurehunt.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the Great Iowa Treasure Hunt portal by your name',
                  'Review matches and select your properties',
                  'Click to start a claim and confirm the property details',
                  'Complete the claimant information form online',
                  'Upload the required identity and address documents',
                  'Submit and note your claim ID for tracking']},
 'ID': {'agency': 'Idaho State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming directly with the Idaho State Treasurer is free.',
        'name': 'Idaho',
        'portal_url': 'https://yourmoney.idaho.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search YourMoney.idaho.gov by entering your name',
                  'Select any properties from the results that are yours',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload proof of identity and proof of address as requested',
                  'Submit the claim and note the claim ID for tracking']},
 'IL': {'agency': 'Illinois State Treasurer (I-Cash)',
        'free_note': "The Illinois Treasurer's I-Cash program is free to search and claim.",
        'name': 'Illinois',
        'portal_url': 'https://icash.illinoistreasurer.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search I-Cash by entering your name',
                  'Review matches and select the properties that belong to you',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required ID and proof-of-address documents (many claims are processed '
                  'without paperwork)',
                  'Submit and use your claim ID to check status']},
 'IN': {'agency': 'Indiana Office of the Attorney General, Unclaimed Property Division',
        'free_note': 'Indiana returns unclaimed property for free directly through the Attorney '
                     'General.',
        'name': 'Indiana',
        'portal_url': 'https://www.indianaunclaimed.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search IndianaUnclaimed.gov by entering your name',
                  'Select the properties from the list that appear to be yours',
                  'Begin the claim and confirm the selected properties',
                  'Fill out the online claimant information form',
                  'Upload proof of identity and proof of address as instructed',
                  'Submit the claim and record the claim ID for status updates']},
 'KS': {'agency': 'Kansas State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming with the Kansas State Treasurer is free.',
        'name': 'Kansas',
        'portal_url': 'https://kansascash.ks.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search KansasCash by entering your name',
                  'Select any matching properties that are yours',
                  'Start the claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload proof of identity and proof of address as requested',
                  'Submit the claim and keep the claim ID to follow up']},
 'KY': {'agency': 'Kentucky State Treasury, Unclaimed Property Division',
        'free_note': 'Kentucky returns property to owners at no cost.',
        'name': 'Kentucky',
        'portal_url': 'https://kyclaims.unclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the portal by entering your name',
                  'Review matches and select the properties you want to claim',
                  'Begin the claim and confirm the property details',
                  'Fill in the online claimant information form',
                  'Upload required ID and proof-of-address documents',
                  'Submit the claim and record the claim ID for status checks']},
 'LA': {'agency': 'Louisiana Department of the Treasury, Unclaimed Property Division',
        'free_note': 'Claiming directly with the Louisiana Treasury is free.',
        'name': 'Louisiana',
        'portal_url': 'https://louisiana.findyourunclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the portal by entering your name',
                  'Select any properties from the results that belong to you',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload or mail the required identity and address documents',
                  'Submit and note your claim ID for tracking']},
 'MA': {'agency': 'Massachusetts State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming through FindMassMoney is free.',
        'name': 'Massachusetts',
        'portal_url': 'https://findmassmoney.com/',
        'processing_time': '30-90 days',
        'steps': ['Search FindMassMoney by entering your name',
                  'Review matches and select the properties you want to claim',
                  'Click to start a claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required ID and proof-of-address documents',
                  'Submit and note your claim ID for status tracking']},
 'MD': {'agency': 'Comptroller of Maryland, Unclaimed Property Unit',
        'free_note': 'Maryland does not charge owners to search for or claim property.',
        'name': 'Maryland',
        'portal_url': 'https://interactive.marylandtaxes.gov/unclaimedproperty/',
        'processing_time': '30-90 days',
        'steps': ['Search the Maryland Comptroller portal by entering your name',
                  'Select the properties from the list that are yours',
                  'Begin the claim and confirm the selection',
                  'Complete the online claimant form with your details',
                  'Print, sign, and mail the claim form with required documents',
                  'Submit and retain the claim reference to follow up']},
 'ME': {'agency': 'Office of the Maine State Treasurer, Unclaimed Property Division',
        'free_note': 'The Maine State Treasurer returns property for free.',
        'name': 'Maine',
        'portal_url': 'https://www.maineunclaimedproperty.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search MaineUnclaimedProperty.gov by entering your name',
                  'Review the matching records and select your properties',
                  'Start the claim and confirm the property details',
                  'Complete the claimant information form online',
                  'Upload proof of identity and proof of address as requested',
                  'Submit the claim and keep your claim ID to check status']},
 'MI': {'agency': 'Michigan Department of Treasury, Unclaimed Property Division',
        'free_note': 'Michigan returns unclaimed property to owners at no cost.',
        'name': 'Michigan',
        'portal_url': 'https://unclaimedproperty.michigan.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the Michigan Treasury portal by entering your name',
                  'Select any matching properties that belong to you',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit the claim and record the claim ID for tracking']},
 'MN': {'agency': 'Minnesota Department of Commerce, Unclaimed Property Program',
        'free_note': 'Minnesota Commerce returns property for free; no fee to search or claim.',
        'name': 'Minnesota',
        'portal_url': 'https://mn.gov/commerce/money/unclaimed-property/',
        'processing_time': '30-90 days',
        'steps': ['Open the Minnesota Commerce portal and go to the unclaimed property search',
                  'Search by your name and select matching properties',
                  'Begin the claim and confirm the property details',
                  'Complete the claimant information form online',
                  'Upload proof of identity and proof of address as requested',
                  'Submit the claim and keep your claim ID to follow up']},
 'MO': {'agency': 'Missouri State Treasurer (Show Me Money)',
        'free_note': 'Searching and claiming with the Missouri State Treasurer is free.',
        'name': 'Missouri',
        'portal_url': 'https://treasurer.mo.gov/UnclaimedProperty/',
        'processing_time': '30-90 days',
        'steps': ['Search the Missouri Treasurer portal by entering your name',
                  'Review matches and select the properties that are yours',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload proof of identity and proof of address as instructed',
                  'Submit the claim and record the claim ID for tracking']},
 'MS': {'agency': 'Mississippi State Treasury, Unclaimed Property Division',
        'free_note': 'The Mississippi State Treasury never charges owners to claim their property.',
        'name': 'Mississippi',
        'portal_url': 'https://treasury.ms.gov/for-citizens/unclaimed-property/',
        'processing_time': '30-90 days',
        'steps': ['Open the Mississippi Treasury page and launch the unclaimed property search',
                  'Search by your name and select your properties',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail the required identity and address documents',
                  'Submit and note your claim ID for status checks']},
 'MT': {'agency': 'Montana Department of Revenue, Unclaimed Property Program',
        'free_note': 'Montana returns property to owners at no charge.',
        'name': 'Montana',
        'portal_url': 'https://mtrevenue.gov/unclaimed-property/',
        'processing_time': '30-90 days',
        'steps': ['Open the Montana Department of Revenue unclaimed property page and launch the '
                  'search',
                  'Search by your name and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail required identity and proof-of-address documents',
                  'Submit and keep your claim reference to follow up']},
 'NC': {'agency': 'North Carolina Department of State Treasurer (NCCash)',
        'free_note': 'NCCash is free; the State Treasurer never charges to return property.',
        'name': 'North Carolina',
        'portal_url': 'https://www.nccash.com/',
        'processing_time': '30-90 days',
        'steps': ['Search NCCash by entering your name',
                  'Select the properties from the results that are yours',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit the claim and record the claim ID for tracking']},
 'ND': {'agency': 'North Dakota Department of Trust Lands, Unclaimed Property Division',
        'free_note': 'North Dakota returns property to owners at no charge.',
        'name': 'North Dakota',
        'portal_url': 'https://unclaimedproperty.nd.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the North Dakota portal by entering your name',
                  'Review matches and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and keep your claim ID to check status']},
 'NE': {'agency': 'Nebraska State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming with the Nebraska State Treasurer is free.',
        'name': 'Nebraska',
        'portal_url': 'https://treasurer.nebraska.gov/up/',
        'processing_time': '30-90 days',
        'steps': ['Open the Nebraska Treasurer unclaimed property page and start the search',
                  'Search by your name and select matching properties',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload proof of identity and proof of address as requested',
                  'Submit the claim and note your claim ID for tracking']},
 'NH': {'agency': 'New Hampshire State Treasury, Abandoned Property Division',
        'free_note': 'New Hampshire returns property to owners at no cost.',
        'name': 'New Hampshire',
        'portal_url': 'https://newhampshire.findyourunclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the portal by entering your name',
                  'Review matches and select the properties you want to claim',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload required ID and proof-of-address documents',
                  'Submit the claim and record the claim ID for status checks']},
 'NJ': {'agency': 'New Jersey Department of the Treasury, Unclaimed Property Administration',
        'free_note': 'New Jersey does not charge owners to search for or claim property.',
        'name': 'New Jersey',
        'portal_url': 'https://unclaimedfunds.nj.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the New Jersey portal by entering your name',
                  'Select any matching properties that belong to you',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit the claim and note your claim ID for tracking']},
 'NM': {'agency': 'New Mexico Taxation and Revenue Department, Unclaimed Property Unit',
        'free_note': 'Claiming directly with the New Mexico Taxation and Revenue Department is '
                     'free.',
        'name': 'New Mexico',
        'portal_url': 'https://nmclaims.unclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the New Mexico portal by entering your name',
                  'Review matches and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and keep your claim ID to follow up']},
 'NV': {'agency': 'Nevada State Treasurer, Unclaimed Property Division',
        'free_note': 'The Nevada State Treasurer returns property for free.',
        'name': 'Nevada',
        'portal_url': 'https://www.nevadatreasurer.gov/Unclaimed_Property/UP_Home/',
        'processing_time': '30-90 days',
        'steps': ['Open the Nevada Treasurer unclaimed property page and launch the search',
                  'Search by your name and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail the required identity and address documents',
                  'Submit and keep the claim ID to check status']},
 'NY': {'agency': 'Office of the New York State Comptroller, Office of Unclaimed Funds',
        'free_note': 'Searching and claiming with the NY State Comptroller is free.',
        'name': 'New York',
        'portal_url': 'https://www.osc.ny.gov/unclaimed-funds',
        'processing_time': '30-90 days',
        'steps': ['Open the NY Comptroller Unclaimed Funds page and start the search',
                  'Search by your name and select matching properties',
                  'Click to begin a claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required ID and proof-of-address documents (some claims need no '
                  'paperwork)',
                  'Submit and note your claim ID for status checks']},
 'OH': {'agency': 'Ohio Department of Commerce, Division of Unclaimed Funds',
        'free_note': 'Ohio returns unclaimed funds for free; no fee to search or claim directly.',
        'name': 'Ohio',
        'portal_url': 'https://unclaimedfunds.ohio.gov/',
        'processing_time': '30-120 days',
        'steps': ['Search the Ohio Unclaimed Funds portal by entering your name',
                  'Select any matching properties that belong to you',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload or mail the required identity and address documents',
                  'Submit the claim and note your claim ID for tracking']},
 'OK': {'agency': 'Oklahoma State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming with the Oklahoma State Treasurer is free.',
        'name': 'Oklahoma',
        'portal_url': 'https://oklahoma.gov/treasurer/unclaimed-property.html',
        'processing_time': '30-90 days',
        'steps': ['Open the Oklahoma Treasurer unclaimed property page and launch the search',
                  'Search by your name and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the claimant information form online',
                  'Upload or mail proof of identity and proof of address',
                  'Submit and keep your claim ID to follow up']},
 'OR': {'agency': 'Oregon State Treasury, Unclaimed Property Program',
        'free_note': 'Oregon State Treasury returns property to owners at no cost.',
        'name': 'Oregon',
        'portal_url': 'https://unclaimed.oregon.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the Oregon portal by entering your name',
                  'Review matches and select the properties that are yours',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit the claim and record the claim ID for status checks']},
 'PA': {'agency': 'Pennsylvania Treasury, Bureau of Unclaimed Property',
        'free_note': 'Pennsylvania Treasury returns property for free; no fee to search or claim.',
        'name': 'Pennsylvania',
        'portal_url': 'https://unclaimedproperty.patreasury.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the Pennsylvania Treasury portal by entering your name',
                  'Select any matching properties that belong to you',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit and note your claim ID for tracking']},
 'RI': {'agency': 'Rhode Island Office of the General Treasurer (Find RI Money)',
        'free_note': 'Searching and claiming with the Rhode Island Treasurer is free.',
        'name': 'Rhode Island',
        'portal_url': 'https://www.findrimoney.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search FindRIMoney by entering your name',
                  'Review matches and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and keep your claim ID to follow up']},
 'SC': {'agency': 'South Carolina Office of the State Treasurer (Palmetto Payback)',
        'free_note': 'South Carolina returns property for free through the State Treasurer.',
        'name': 'South Carolina',
        'portal_url': 'https://southcarolina.findyourunclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the South Carolina portal by entering your name and city',
                  'Select the properties from the results that are yours',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit the claim and use your claim ID to check status']},
 'SD': {'agency': 'South Dakota Office of the State Treasurer, Unclaimed Property Division',
        'free_note': 'South Dakota returns property to owners at no charge.',
        'name': 'South Dakota',
        'portal_url': 'https://southdakota.findyourunclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the South Dakota portal by entering your name',
                  'Review matches and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and keep your claim ID for tracking']},
 'TN': {'agency': 'Tennessee Department of Treasury, Unclaimed Property Division (ClaimItTN)',
        'free_note': 'ClaimItTN is free; the Tennessee Treasury never charges to return property.',
        'name': 'Tennessee',
        'portal_url': 'https://claimittn.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search ClaimItTN by entering your name',
                  'Select any matching properties that belong to you',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and note your claim ID for status checks']},
 'TX': {'agency': 'Texas Comptroller of Public Accounts (ClaimItTexas)',
        'free_note': 'ClaimItTexas is free; the Texas Comptroller never charges owners to claim.',
        'name': 'Texas',
        'portal_url': 'https://www.claimittexas.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search ClaimItTexas by entering your name',
                  'Select the properties from the results that are yours',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit the claim and record the claim ID for tracking']},
 'UT': {'agency': 'Utah State Treasurer, Unclaimed Property Division (MyCash)',
        'free_note': "Utah's MyCash program returns property for free.",
        'name': 'Utah',
        'portal_url': 'https://mycash.utah.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search MyCash by entering your name',
                  'Review matches and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and keep your claim ID to follow up']},
 'VA': {'agency': 'Virginia Department of the Treasury, Unclaimed Property Program',
        'free_note': 'Virginia returns property to owners at no charge.',
        'name': 'Virginia',
        'portal_url': 'https://www.vamoneysearch.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search Vamoneysearch by entering your name',
                  'Review matches and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and keep your claim ID for tracking']},
 'VT': {'agency': 'Office of the Vermont State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming with the Vermont State Treasurer is free.',
        'name': 'Vermont',
        'portal_url': 'https://vermont.unclaimedproperty.com/',
        'processing_time': '30-90 days',
        'steps': ['Search the Vermont portal by entering your name',
                  'Select any matching properties that belong to you',
                  'Click to start a claim and confirm the selection',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit and note your claim ID for status checks']},
 'WA': {'agency': 'Washington State Department of Revenue, Unclaimed Property Section',
        'free_note': 'Washington DOR returns property for free; no fee to search or claim.',
        'name': 'Washington',
        'portal_url': 'https://ucp.dor.wa.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the Washington DOR portal by entering your name',
                  'Select the properties from the results that are yours',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents (many claims need no '
                  'paperwork)',
                  'Submit and note your claim ID for status checks']},
 'WI': {'agency': 'Wisconsin Department of Revenue, Unclaimed Property Unit',
        'free_note': 'Wisconsin DOR returns property to owners for free.',
        'name': 'Wisconsin',
        'portal_url': 'https://www.revenue.wi.gov/Pages/UnclaimedProperty/Home.aspx',
        'processing_time': '30-90 days',
        'steps': ['Open the Wisconsin DOR unclaimed property page and launch the search',
                  'Search by your name and select matching properties',
                  'Start the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload required identity and proof-of-address documents',
                  'Submit and record the claim ID for tracking']},
 'WV': {'agency': "West Virginia State Treasurer's Office, Unclaimed Property Division",
        'free_note': 'The West Virginia State Treasurer returns property at no cost.',
        'name': 'West Virginia',
        'portal_url': 'https://www.wvunclaimedproperty.gov/',
        'processing_time': '30-90 days',
        'steps': ['Search the West Virginia portal by entering your name',
                  'Review matches and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit and keep your claim ID to follow up']},
 'WY': {'agency': 'Wyoming State Treasurer, Unclaimed Property Division',
        'free_note': 'Searching and claiming with the Wyoming State Treasurer is free.',
        'name': 'Wyoming',
        'portal_url': 'https://statetreasurer.wyo.gov/unclaimed-property/',
        'processing_time': '30-90 days',
        'steps': ['Open the Wyoming Treasurer unclaimed property page and launch the search portal',
                  'Search by your name and select your properties',
                  'Begin the claim and confirm the property details',
                  'Complete the online claimant information form',
                  'Upload or mail proof of identity and proof of address',
                  'Submit and keep your claim ID to check status']}}
